spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/doubleshop
    username: dev
    password: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: user.accnt.update@gmail.com
    password: zeppelin123$
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mybatis:
  config-location: classpath:mybatis-config.xml
logging:
  level:
    org:
      springframework: info
azure:
  keyvault:
    uri: https://usain-vault.vault.azure.net/
    client-id: 463496c2-5e54-4a78-889e-55af8bb8ca48
    client-key: 8hH7Q~v.2kL._sw2metsuD~j--1BAHak5b0lq
    tenant-id: 4f2d7d69-dc78-4e51-bc6d-b2b342840dee
    refresh-interval: 1800000
    enabled: true
    secret-keys: account-sid, auth-token, sender-num
