CREATE TABLE IF NOT EXISTS `ARTICLES`(
    `id`          BiGINT NOT NULL AUTO_INCREMENT,
    `title`       VARCHAR(100) NOT NULL,
    `author`      VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE  IF NOT EXISTS `ITEM`
(
    id                         bigint         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                       varchar(50)    NOT NULL,
    description                varchar(50)    NOT NULL,
    price                      integer        NOT NULL,
    unit                       varchar(50)    NULL,
    volume                     varchar(50)    NULL,
    length                     varchar(50)    NULL,
    package_type               varchar(50)    NULL,
    certificate_of_analysis    varchar(50)    NULL,
    expiration                 varchar(50)    NULL,
    price_per_100g             integer        NULL,
    allergic_issue             varchar(50)    NULL,
    model_serial_no            bigint         NULL,
    rate_point                 integer        NULL,
    search_keyword             varchar(50)    NULL,
    stock                      integer        NULL,
    discount_price             integer        NULL,
    oneday_eligible           boolean        NULL,
    fresh_eligible            boolean        NULL,
    CONSTRAINT PK_ITEM PRIMARY KEY (id)
);