CREATE TABLE  IF NOT EXISTS `ITEM`
(
    id                         bigint         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                       varchar(50)    NOT NULL,
    description                varchar(50)    NOT NULL,
    price                      integer        NOT NULL,
    unit                       varchar(50)    NULL DEFAULT '',
    volume                     varchar(50)    NULL DEFAULT '',
    length                     varchar(50)    NULL DEFAULT '',
    package_type               varchar(50)    NULL DEFAULT '',
    origin    varchar(50)    NULL DEFAULT '',
    expiration                 varchar(50)    NULL DEFAULT '',
    price_per_100g             integer        NULL DEFAULT 0,
    allergic_info             varchar(50)    NULL DEFAULT '',
    model_serial_no            varchar(50)    NULL DEFAULT '',
    rating                 integer        NULL DEFAULT 0,
    search_keyword             varchar(50)    NULL DEFAULT '',
    stock                      integer        NULL DEFAULT 0,
    discount_price             integer        NULL DEFAULT 0,
    oneday_eligible           boolean        NULL DEFAULT false,
    fresh_eligible            boolean        NULL DEFAULT false,
    CONSTRAINT PK_ITEM PRIMARY KEY (id)
);