name: double-shop CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Clean with Maven
        run: mvn --batch-mode --update-snapshots clean
      - name: Verify with Maven
        run: mvn --batch-mode --update-snapshots verify
